import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Provider } from '@/shared/ui/chakra/provider';
import { SwitchThemeContext } from '@/context/SwitchTheme';
import './globals.css';

const montserrat = Montserrat({
   weight: ['300', '400', '500', '600', '700'],
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-montserrat',
   fallback: ['Arial', 'sans-serif'],
});

export const metadata: Metadata = {
   title: 'Atomic Code',
   description: 'Generated by atomic code devs',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning className={montserrat.variable}>
         <body className="overflow-auto">
            <Provider>
               <SwitchThemeContext>{children}</SwitchThemeContext>
            </Provider>
         </body>
      </html>
   );
}
