import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Provider } from '@/ui/chakra/provider';
import ThemeLayout from '@/config/ThemeLayout/ThemeLayout';
import './globals.css';
import FooterLayout from '@/components/Footer/cells/FooterLayout';

const montserrat = Montserrat({
   weight: ['300', '400', '500', '600', '700'],
   subsets: ['latin'],
   display: 'swap',
   fallback: ['Arial', 'sans-serif'],
});

export const metadata: Metadata = {
   title: 'Atomic Code',
   description: 'Generated by atomic code devs',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={`${Object.values(montserrat.style).join(' ')} antialiased`}>
            <Provider>
               <ThemeLayout>{children}</ThemeLayout>
               <FooterLayout />
            </Provider>
         </body>
      </html>
   );
}
