name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Find atomic-frontend directory path
        id: find_dir
        run: |
          DIR=$(find . -type d -name atomic-frontend | head -n 1)
          echo "directory=$DIR" >> $GITHUB_OUTPUT

      - name: Build Docker image and save to tar
        run: |
          cd ${{ steps.find_dir.outputs.directory }}

          # Передаем переменные окружения через --build-arg
          docker build --build-arg API_URL=${{ secrets.API_URL }} \
                       -t atomic-tech.ru .
          docker save atomic-tech.ru -o atomic-tech.ru.tar

      - name: Rsync tar and project to server
        run: |
          rsync -avz --delete ${{ steps.find_dir.outputs.directory }}/ root@85.193.82.242:/var/www/atomic-tech.ru/
          rsync -avz ${{ steps.find_dir.outputs.directory }}/atomic-tech.ru.tar root@85.193.82.242:/var/www/atomic-tech.ru/

      - name: Load image and run container on remote
        run: |
          ssh root@85.193.82.242 << 'EOF'
            docker stop atomic-tech.ru || true
            docker rm atomic-tech.ru || true
            docker rmi atomic-tech.ru || true
            docker system prune -a -f
            cd /var/www/atomic-tech.ru
            docker load -i atomic-tech.ru.tar
            docker run -d --name atomic-tech.ru -p 3000:3000 atomic-tech.ru
            systemctl reload nginx || systemctl restart nginx
          EOF
